version: '3.8'

services:
  # Database Service
  postgres:
    image: postgres:15-alpine
    container_name: saas_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-saas_platform}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432" # Exposed for remote access (PgAdmin)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas_network

  # Backend API Service
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: saas_api
    restart: always
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows access to host machine
    environment:
      # Use "postgres" host if using docker DB, or "host.docker.internal" if using host DB
      DATABASE_URL: ${DATABASE_URL:-postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-saas_platform}?schema=public}
      JWT_SECRET: ${JWT_SECRET:-supersecretkey}
      PORT: 3000
      # AI & Vector DB
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      # Email Service
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - saas_network

  # Frontend Client Service
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    container_name: saas_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - saas_network

volumes:
  postgres_data:


networks:
  saas_network:
    driver: bridge
